version: '3.4'

networks:
  dev:
    

volumes:
  app_data:


services:
  api:
    container_name: dzik.api
    depends_on: 
      - "db"
    image: ${DOCKER_REGISTRY-}host
    build:
      context: .
      dockerfile: src/Host/Dockerfile
    environment:
      - DatabaseSettings__ConnectionString=User ID=dziku;Password=dziku123;Host=dzik.db;Port=5432;Database=dzik;
    ports:
      - 8080:8080
    networks: 
      - dev

  db:
    container_name: dzik.db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=dzik
      - POSTGRES_USER=dziku
      - POSTGRES_PASSWORD=dziku123
    volumes:
      - app_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - dev