@host = http://localhost:8080

POST {{host}}/auth/register
Content-Type: application/json
accept: application/json

{
  "firstName": "Mateusz",
  "lastName": "Gutowski",
  "userName": "matelko",
  "email": "mateusz@gmail.com",
  "password": "qwe123",
  "phoneNumber": "123123123"
}

###

POST {{host}}/auth/login
Content-Type: application/json
accept: application/json

{
  "email": "mateusz@gmail.com",
  "password": "qwe123",
  "isPersistent": true
}